In [ ]:
#ORDER LEVEL CORRELATION ANALYSIS

In [6]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://username:password@localhost:5432/ecommerce_db"
)

In [99]:
query = """
SELECT
    order_id,
    customer_unique_id,
    order_purchase_date,
    delivered_date,
    estimated_delivery_date,
    total_payment
FROM ecommerce_order_level
"""

order_df = pd.read_sql(
    query,
    engine
)

In [100]:
order_df.head()

,order_id,customer_unique_id,order_purchase_date,delivered_date,estimated_delivery_date,total_payment
0,00018f77f2f0320c557190d7a144bdd3,eb28e67c4c0b83846050ddfb8a35d051,2017-04-26,2017-05-12,2017-05-15,259.83
1,000229ec398224ef6ca0657da4fc703e,3818d81c6709e39d06b2738a8d3a2474,2018-01-14,2018-01-22,2018-02-05,216.87
2,00061f2a7bc09da83e415a52dc8a4af1,107e6259485efac66428a56f10801f4f,2018-03-24,2018-03-29,2018-04-09,68.87
3,00063b381e2406b52ad429470734ebd5,3fb97204945ca0c01bcf3eee6031c5f1,2018-07-27,2018-08-07,2018-08-07,57.98
4,0006ec9db01a64e59a68b2c340bf65a7,7ed0ea20347f67fe61d1c99fdf8556ae,2018-07-24,2018-07-31,2018-08-22,97.32

In [101]:
order_df['order_purchase_date'] = pd.to_datetime(
    order_df['order_purchase_date']
)

order_df['delivered_date'] = pd.to_datetime(
    order_df['delivered_date']
)

order_df['estimated_delivery_date'] = pd.to_datetime(
    order_df['estimated_delivery_date']
)

In [102]:
order_df['delivery_days'] = (
    order_df['delivered_date']
    - order_df['order_purchase_date']
).dt.days

order_df['estimated_window'] = (
    order_df['estimated_delivery_date']
    - order_df['order_purchase_date']
).dt.days

order_df['delivery_delay'] = (
    order_df['delivered_date']
    - order_df['estimated_delivery_date']
).dt.days

order_df.head()

,order_id,customer_unique_id,order_purchase_date,delivered_date,estimated_delivery_date,total_payment,delivery_days,estimated_window,delivery_delay
0,00018f77f2f0320c557190d7a144bdd3,eb28e67c4c0b83846050ddfb8a35d051,2017-04-26,2017-05-12,2017-05-15,259.83,16.0,19,-3.0
1,000229ec398224ef6ca0657da4fc703e,3818d81c6709e39d06b2738a8d3a2474,2018-01-14,2018-01-22,2018-02-05,216.87,8.0,22,-14.0
2,00061f2a7bc09da83e415a52dc8a4af1,107e6259485efac66428a56f10801f4f,2018-03-24,2018-03-29,2018-04-09,68.87,5.0,16,-11.0
3,00063b381e2406b52ad429470734ebd5,3fb97204945ca0c01bcf3eee6031c5f1,2018-07-27,2018-08-07,2018-08-07,57.98,11.0,11,0.0
4,0006ec9db01a64e59a68b2c340bf65a7,7ed0ea20347f67fe61d1c99fdf8556ae,2018-07-24,2018-07-31,2018-08-22,97.32,7.0,29,-22.0

In [73]:
order_df = order_df.dropna()
order_df.isnull().sum()

order_id                   0
order_purchase_date        0
delivered_date             0
estimated_delivery_date    0
total_payment              0
delivery_days              0
estimated_window           0
delivery_delay             0
dtype: int64

In [74]:
order_df =(
    order_df.rename(
        columns = {
            'total_payment' : 'revenue'
        }
    )
)

In [76]:
correlation_matrix_order = (
    order_df[
        [
            'revenue',
            'delivery_days',
            'estimated_window',
            'delivery_delay'
        ]
    ]
    .corr()
)

In [77]:
correlation_matrix_order

                   revenue  delivery_days  estimated_window  delivery_delay
revenue           1.000000       0.069893          0.096847       -0.017743
delivery_days     0.069893       1.000000          0.384403        0.607580
estimated_window  0.096847       0.384403          1.000000       -0.499677
delivery_delay   -0.017743       0.607580         -0.499677        1.000000

In [42]:
#ITEM LEVEL CORRELATION ANALYSIS

In [92]:
query1 = """
SELECT
    price,
    freight_value,
    shipping_ratio,
    product_name_length,
    product_description_length
FROM ecommerce_order_item_level
"""

order_item_df = pd.read_sql(
    query1,
    engine
)

In [93]:
order_item_df.head()

,price,freight_value,shipping_ratio,product_name_length,product_description_length
0,69.90,23.07,0.33,57.0,689.0
1,49.89,8.72,0.17,55.0,352.0
2,58.90,13.29,0.23,58.0,598.0
3,99.00,13.71,0.14,55.0,312.0
4,29.99,16.32,0.54,44.0,232.0

In [94]:
order_item_df.isnull().sum()

price                            0
freight_value                    0
shipping_ratio                   0
product_name_length           1603
product_description_length    1603
dtype: int64

In [95]:
order_item_df = order_item_df.dropna()
order_item_df.isnull().sum()

price                         0
freight_value                 0
shipping_ratio                0
product_name_length           0
product_description_length    0
dtype: int64

In [96]:
correlation_matrix_item = (
    order_item_df[
        [
            'price',
            'freight_value',
            'shipping_ratio',
            'product_name_length',
            'product_description_length'
        ]
    ]
    .corr()
)

In [97]:
correlation_matrix_item

,price,freight_value,shipping_ratio,product_name_length,product_description_length
price,1.000000,0.414426,-0.292222,0.017001,0.198166
freight_value,0.414426,1.000000,0.088804,0.023611,0.093855
shipping_ratio,-0.292222,0.088804,1.000000,-0.057412,-0.122646
product_name_length,0.017001,0.023611,-0.057412,1.000000,0.091524
product_description_length,0.198166,0.093855,-0.122646,0.091524,1.000000

In [116]:
correlation_matrix_item = (
    correlation_matrix_item
    .reset_index()
)
correlation_matrix_item

,index,price,freight_value,shipping_ratio,product_name_length,product_description_length
0,price,1.000000,0.414426,-0.292222,0.017001,0.198166
1,freight_value,0.414426,1.000000,0.088804,0.023611,0.093855
2,shipping_ratio,-0.292222,0.088804,1.000000,-0.057412,-0.122646
3,product_name_length,0.017001,0.023611,-0.057412,1.000000,0.091524
4,product_description_length,0.198166,0.093855,-0.122646,0.091524,1.000000

In [117]:
correlation_matrix_item.to_sql(
    'correlation_matrix_item',
    engine,
    if_exists='replace',
    index=False
)

5

In [118]:
correlation_matrix_order = (
    correlation_matrix_order
    .reset_index()
)
correlation_matrix_order

              index   revenue  delivery_days  estimated_window  delivery_delay
0           revenue  1.000000       0.069893          0.096847       -0.017743
1     delivery_days  0.069893       1.000000          0.384403        0.607580
2  estimated_window  0.096847       0.384403          1.000000       -0.499677
3    delivery_delay -0.017743       0.607580         -0.499677        1.000000

In [119]:
correlation_matrix_order.to_sql(
    'correlation_matrix_order',
    engine,
    if_exists='replace',
    index=False
)

4